### ISSUE TITLE
Is it possible to serve images

### ISSUE THREAD

**Issue by savpek** [bodsch/docker-markdown-service#4]
I tested solution and it seems nice, however i mounted subfolder /img/ with few png:s. They return 404, is it possible to serve images through same server?

**Comment by bodsch** [comment]
sure. it should be possible.
i will see, what can i do.

**Comment by bodsch** [comment]
This docker container use the [ruby-markdown-service](https://github.com/bodsch/ruby-markdown-service).
I fill there your issue

**Comment by bodsch** [comment]
fixed in the ruby code
